PACKAGE_NAME="usbpoll-oc"
PACKAGE_VERSION="1.4"
MAKE[0]="make KERNEL_SOURCE_DIR=$kernel_source_dir"
CLEAN="make KERNEL_SOURCE_DIR=$kernel_source_dir clean"
BUILT_MODULE_NAME[0]="usbpoll_oc"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
